<?php
echo '<html>';
echo '<head>';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>';
echo '<script src="https://code.jquery.com/jquery-3.7.0.js"></script>';
echo '<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->';
echo '<link rel="stylesheet" href="feedback.css">';
echo '<link rel="stylesheet" href="boot.css">';
echo '<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"';
echo 'integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />';
echo '<script src="https://code.jquery.com/jquery-3.6.0.min.js"';
echo 'integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"';
echo 'integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"';
echo 'crossorigin="anonymous"></script>';
echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"';
echo 'integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"';
echo 'crossorigin="anonymous"></script>';
echo '</head>';
echo '';
echo '<body>';
echo '<center>';
echo '<div class="feed-cont">';
echo '<h1 style="font-family:Times New Roman;font-size: 40;text-align: left;"><b>Review & Rating</b></h1>';
echo '<div class="feed-card">';
echo '';
echo '<div class="row">';
echo '';
echo '<div class="col-sm-4 text-center">';
echo '<h1 style="color:orange;font-family: arial;font-size: 40;"><b><span id="average_rating">0.0</span> / 5</b>';
echo '</h1>';
echo '<div class="mb-3"><i class="fas fa-star star-light mr-1 main_star"></i><i';
echo 'class="fas fa-star star-light mr-1 main_star"></i><i';
echo 'class="fas fa-star star-light mr-1 main_star"></i><i';
echo 'class="fas fa-star star-light mr-1 main_star"></i><i class="fas fa-star star-light mr-1 main_star"></i>';
echo '</div>';
echo '<h2 style="font-weight: normal;font-size: 30;"><span id="total_review">0</span> Review</h2>';
echo '</div>';
echo '';
echo '<div class="col-sm-4">';
echo '<p>';
echo '<div class="progress-label-left"><b>5</b><i class="fas fa-star text-warning"></i></div>';
echo '<div class="progress-label-right">(<span id="total_five_star_review">0</span>)</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0"';
echo 'aria-valuemax="100" id="five_star_progress"></div>';
echo '</div>';
echo '</p>';
echo '<p>';
echo '<div class="progress-label-left"><b>4</b><i class="fas fa-star text-warning"></i></div>';
echo '<div class="progress-label-right">(<span id="total_four_star_review">0</span>)</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0"';
echo 'aria-valuemax="100" id="four_star_progress"></div>';
echo '</div>';
echo '</p>';
echo '<p>';
echo '<div class="progress-label-left"><b>3</b><i class="fas fa-star text-warning"></i></div>';
echo '<div class="progress-label-right">(<span id="total_three_star_review">0</span>)</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0"';
echo 'aria-valuemax="100" id="three_star_progress"></div>';
echo '</div>';
echo '</p>';
echo '<p>';
echo '<div class="progress-label-left"><b>2</b><i class="fas fa-star text-warning"></i></div>';
echo '<div class="progress-label-right">(<span id="total_two_star_review">0</span>)</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0"';
echo 'aria-valuemax="100" id="two_star_progress"></div>';
echo '</div>';
echo '</p>';
echo '<p>';
echo '<div class="progress-label-left"><b>1</b><i class="fas fa-star text-warning"></i></div>';
echo '<div class="progress-label-right">(<span id="total_one_star_review">0</span>)</div>';
echo '<div class="progress">';
echo '<div class="progress-bar bg-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0"';
echo 'aria-valuemax="100" id="one_star_progress"></div>';
echo '</div>';
echo '</p>';
echo '</div>';
echo '<div class="col-sm-4 text-center">';
echo '<h2 style="font-family:serif;font-weight: normal;font-size: 35;">Share Your Experience Here!';
echo '</h2>';
echo '<button type="button" name="add_review" id="add_review" class="feed-btn">Review</button>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</center>';
echo '<div class="mt-5" id="review_content"></div>';
echo '</div>';
echo '<script>';
echo '$(document).ready(function () {';
echo 'var rating_data = 0;';
echo '';
echo '$("#add_review").click(function () {';
echo '$("#review_modal").modal("show");';
echo '});';
echo '';
echo '$(document).on("mouseenter", ".submit_star", function () {';
echo 'var rating = $(this).data("rating");';
echo '';
echo 'reset_background();';
echo '';
echo 'for (var count = 1; count <= rating; count++) {';
echo '$("#submit_star_" + count).addClass("text-warning");';
echo '}';
echo '});';
echo '';
echo 'function reset_background() {';
echo 'for (var count = 1; count <= 5; count++) {';
echo '$("#submit_star_" + count).addClass("star-light");';
echo '';
echo '$("#submit_star_" + count).removeClass("text-warning");';
echo '}';
echo '}';
echo '';
echo '$(document).on("mouseleave", ".submit_star", function () {';
echo 'reset_background();';
echo '';
echo 'for (var count = 1; count <= rating_data; count++) {';
echo '$("#submit_star_" + count).removeClass("star-light");';
echo '';
echo '$("#submit_star_" + count).addClass("text-warning");';
echo '}';
echo '});';
echo '';
echo '$(document).on("click", ".submit_star", function () {';
echo 'rating_data = $(this).data("rating");';
echo '});';
echo '';
echo '$("#save_review").click(function () {';
echo 'var user_name = $("#user_name").val();';
echo '';
echo 'var user_review = $("#user_review").val();';
echo '';
echo 'if (user_name == "" || user_review == "") {';
echo 'alert("Please Fill Both Field");';
echo 'return false;';
echo '} else {';
echo '$.ajax({';
echo 'url: "submit_rating.php",';
echo 'method: "POST",';
echo 'data: {';
echo 'rating_data: rating_data,';
echo 'user_name: user_name,';
echo 'user_review: user_review,';
echo '},';
echo 'success: function (data) {';
echo '$("#review_modal").modal("hide");';
echo '';
echo 'load_rating_data();';
echo '';
echo 'alert(data);';
echo '},';
echo '});';
echo '}';
echo '});';
echo '';
echo 'load_rating_data();';
echo '';
echo 'function load_rating_data() {';
echo '$.ajax({';
echo 'url: "submit_rating.php",';
echo 'method: "POST",';
echo 'data: { action: "load_data" },';
echo 'dataType: "JSON",';
echo 'success: function (data) {';
echo '$("#average_rating").text(data.average_rating);';
echo '$("#total_review").text(data.total_review);';
echo '';
echo 'var count_star = 0;';
echo '';
echo '$(".main_star").each(function () {';
echo 'count_star++;';
echo 'if (Math.ceil(data.average_rating) >= count_star) {';
echo '$(this).addClass("text-warning");';
echo '$(this).addClass("star-light");';
echo '}';
echo '});';
echo '';
echo '$("#total_five_star_review").text(data.five_star_review);';
echo '';
echo '$("#total_four_star_review").text(data.four_star_review);';
echo '';
echo '$("#total_three_star_review").text(data.three_star_review);';
echo '';
echo '$("#total_two_star_review").text(data.two_star_review);';
echo '';
echo '$("#total_one_star_review").text(data.one_star_review);';
echo '';
echo '$("#five_star_progress").css(';
echo '"width",';
echo '(data.five_star_review / data.total_review) * 100 + "%"';
echo ');';
echo '';
echo '$("#four_star_progress").css(';
echo '"width",';
echo '(data.four_star_review / data.total_review) * 100 + "%"';
echo ');';
echo '$("#three_star_progress").css(';
echo '"width",';
echo '(data.three_star_review / data.total_review) * 100 + "%"';
echo ');';
echo '$("#two_star_progress").css(';
echo '"width",';
echo '(data.two_star_review / data.total_review) * 100 + "%"';
echo ');';
echo '$("#one_star_progress").css(';
echo '"width",';
echo '(data.one_star_review / data.total_review) * 100 + "%"';
echo ');';
echo 'if (data.review_data.length > 0) {';
echo 'var html = "";';
echo 'for (var count = 0; count < data.review_data.length; count++) {';
echo 'html += `<div class="row mb-3">`;';
echo 'html += `<div class="col-sm-11">`;';
echo 'html += `<div class="card">`;';
echo 'html +=';
echo '`<div class="card-header"><b>` +';
echo 'data.review_data[count].user_name +';
echo '"</b></div>";';
echo 'html += `<div class="card-body">`;';
echo 'for (var star = 1; star <= 5; star++) {';
echo 'var class_name = "";';
echo 'if (data.review_data[count].rating >= star) {';
echo 'class_name = "text-warning";';
echo '} else {';
echo 'class_name = "star-light";';
echo '}';
echo 'html += `<i class="fas fa-star ` + class_name + ` mr-1"></i>`;';
echo '}';
echo 'html += "<br />";';
echo 'html += data.review_data[count].user_review;';
echo 'html += "</div>";';
echo 'html +=';
echo '`<div class="card-footer text-right">On ` +';
echo 'data.review_data[count].datetime +';
echo '"</div>";';
echo 'html += "</div>";';
echo 'html += "</div>";';
echo 'html += "</div>";';
echo '}';
echo '$("#review_content").html(html);';
echo '}';
echo '},';
echo '});';
echo '}';
echo '});';
echo '</script>';
echo '</body>';
echo '';
echo '</html>';
echo '';
echo '';
echo '<div id="review_modal" class="modal" tabindex="-1" role="dialog">';
echo '<div class="modal-dialog" role="document">';
echo '<div class="modal-content">';
echo '<div class="modal-header">';
echo '<div class="modal-title" style="text-align: left;font-weight: normal;">Submit Review</div>';
echo '<div><button type="button" class="close" data-dismiss="modal" aria-label="Close">x</button></div>';
echo '</div>';
echo '<div class="modal-body"><center>';
echo '<h2 class="modal-star">';
echo '<i class="fas fa-star star-light submit_star mr-1" id="submit_star_1" data-rating="1"></i>';
echo '<i class="fas fa-star star-light submit_star mr-1" id="submit_star_2" data-rating="2"></i>';
echo '<i class="fas fa-star star-light submit_star mr-1" id="submit_star_3" data-rating="3"></i>';
echo '<i class="fas fa-star star-light submit_star mr-1" id="submit_star_4" data-rating="4"></i>';
echo '<i class="fas fa-star star-light submit_star mr-1" id="submit_star_5" data-rating="5"></i>';
echo '</h2>';
echo '<div class="form-group"><input type="text" name="user_name" id="user_name" class="form-control"';
echo 'placeholder="Enter Your Name"/></div>';
echo '<div class="form-group"><textarea name="user_review" id="user_review" class="form-control"';
echo 'placeholder="Write Your Feedback Here...."></textarea></div>';
echo '<div class="form-group text-center mt-4"><button type="button" class="feed-btn" id="save_review">Submit</button>';
echo '</div></center>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<!-- <script src="feedback.js"></script> -->';
echo '';
?>